
obj-y += ems_base.o


obj-y += board/board_config.o
obj-y += board/am62x/board_config_am62x.o

obj-y += cmd/cmd_updatex.o
obj-y += cmd/cmd_bootk.o
obj-y += cmd/cmd_emsflash.o

obj-y += common/ems_blk.o
obj-y += common/ems_blk_mmc.o
obj-y += common/ems_blk_flash.o
obj-y += common/ems_pack.o

